### ISSUE TITLE
Mod updating

### ISSUE THREAD

**Issue by Nexela** [AlyxMoon/Lunars-Factorio-Mod-Manager#13]
This mod loader is turning out really nice. I just wanted to throw out a few ideas and insights as you add mod portal intergration
#1 the ability for profiles to have multiple config setups. I.E. factorio.exe --config path-to-config

This will allow for easy setup of environments and saves based on what one is doing. i.e my devel environment has a different set of options versus my normal evn. Also it would keep saves separated.
#2 Multiple versions of the mod. including multiples of the same version.
#3 If a mod is extracted chances are it is for config changes don't overwrite/upgrade these changes

I am sure I will think up more when I am in spot where I can't write them down. Keep up the awesome work!

**Comment by AlyxMoon** [comment]
Excellent ideas, I had the second idea planned but the other two are good. Can you clarify what you mean by the first and third though?

By the first, do you mean that a profile isn't just a collection of mods, but a collection of mods+mod config, in the case that you want different configs for a mod?

And the third. Do you mean that when you upgrade a mod that it won't mess with an existing profile/config setup?

**Comment by Nexela** [comment]
1 and 3 are not fully related

1. The --config flag lets you point to a factorio config file containing your settings and application and data directories. This would do something like

`root---factorio.13.15---confighighsettings`
`       |                         |->configlowsettings`
`                                 |->developsettings`

config high and low points the write dir to %appdata%/factorio with different settings
config develop points the write dir to e:\factoriomoddevelop

high and low are using the same set of mods and config is using an different set (for me mostly helper mods)


3.  Going by the way the current mod portal works (which is horrid btw)  if you extract a mod and make changes to it.  Updating the mod in game will overwrite your changes.  So if a mod is extracted don't automatically update it. 

Hopefully that helps clear up some confusions :)

**Comment by AlyxMoon** [comment]
Ah thank you, I get what you mean now. I wasn't aware of the Factorio flags. I think both of these sound like a "version 2.5" kind of thing, and I'll plan for it then.

Number 3 sounds tricky though. I get what you mean, either keeping changes to the mod, or just config changes. If we simply keep the old settings or don't update it, then if there are new config options or code it won't be kept and that's a problem. I'll mull over solutions to implement it well.

And thanks again for the feedback, I really do appreciate it!

# The ToDo:

- [ ] Have a profile keep an instance of Factorio config state.

- [ ] Allow for multiple mod version at once, choose which mod version in profile.

- [ ] Allow user option to keep edited mod code or config settings upon mod update.

**Comment by AlyxMoon** [comment]
Closing due to age and a planned rework
