### ISSUE TITLE
LMM not launching after selecting mod list and exe file

### ISSUE THREAD

**Issue by Timeslice42** [AlyxMoon/Lunars-Factorio-Mod-Manager#58]
After prompting me for the mod-list.json and factorio.exe files LMM just closes. The log file looks like this:
```
9/7/2016, 5:35:13 PM | Beginning initialization of app.
9/7/2016, 5:35:13 PM | Was not able to find config or profiles file.
9/7/2016, 5:35:13 PM | Beginning to create config and profiles files.
9/7/2016, 5:35:13 PM | Prompting user for Factorio modlist.json file.
9/7/2016, 5:35:30 PM | Prompting user for Factorio.exe file.
9/7/2016, 5:35:43 PM | Failed to write config on first time initialization, error: ENOENT
9/7/2016, 5:35:43 PM | There was an error. Not saving app data, closing app.
```

**Comment by AlyxMoon** [comment]
Thank you very much for the log file.

I'm guessing you're on v1.8.5, right? I tried from a fresh install and didn't get the error, but I'll add in some things that might help. Expect an update in a day or two that will fix it, or I'll at least include better logging so I can get to the bottom of it.

**Comment by AlyxMoon** [comment]
In a way, it's a relief you had a problem in the area I've been working on improving the past few days.

Just got update 1.8.6 which should help to fix it outright, or at least give me some better logs so I can help pinpoint the problem.

If you want to give it a go and let me know if the problem is fixed, or send me the log if it doesn't, that would be much appreciated.

Thanks again for trying out the app, hopefully this gets it working for you!

**Comment by Timeslice42** [comment]
Thanks for the quick followup. Here's the error in 1.8.6:
```
9/8/2016, 11:25:03 AM | Was not able to find config file. Creating.
9/8/2016, 11:25:03 AM | Prompting user for Factorio modlist.json file.
9/8/2016, 11:25:52 AM | Prompting user for Factorio.exe file.
9/8/2016, 11:26:34 AM | x_loc not found parsing config, setting a default value and continuing.
9/8/2016, 11:26:34 AM | y_loc not found parsing config, setting a default value and continuing.
9/8/2016, 11:26:34 AM | Error creating Mod Manager class. Error: ENOENT: no such file or directory, open 'F:\AppData\Roaming\Factorio\config\player-data.json'
```

Oddly enough all of those json files are in F:\AppData\Roaming\Factorio\ for me (not config).

**Comment by AlyxMoon** [comment]
Awesome, thanks again for the follow up. That log entry helped tremendously, I appreciate the patience in sending that again. I made a mistake in hardcoding the path to that file. I didn't account for the fact it might be elsewhere for people when I first wrote that bit of code.

Version 1.8.7 will be out in just a minute, and will resolve this. You'll just have to go through one more dialog prompt when you start the app.

**Comment by Timeslice42** [comment]
But how did it end up in a different location? I know I didn't move it. I wonder if the steam version puts it in a different place than the stand-alone version.

**Comment by AlyxMoon** [comment]
That would be my guess. Do you have the Steam or Standalone?

I used to have the standalone then moved to Steam, I know a few things changed location but I can't remember the details.

**Comment by Timeslice42** [comment]
Same. I had standalone and moved to steam.
