### ISSUE TITLE
Program fails after picking files

### ISSUE THREAD

**Issue by Nexela** [AlyxMoon/Lunars-Factorio-Mod-Manager#64]
Win 7 64bit

Am I doing something wrong?  I have tried the past handful of versions and all do the same thing

After running the program I pick the mod-list, pick the exe, (in the latest ver pick the player-data) and then.....

Nothing

I can't even find any error/log files
Let me know what else you need from me.

**Comment by AlyxMoon** [comment]
I've got a few questions for you then.

1 - What was the last version you were running successfully?
2 - Inside the resources/app directory of the app, there isn't any json file generated at all? But it does go through every dialog?
3 - When you updated from a version that worked, how did you update? Did you just replace the files from the new version?

Sorry about the problems. My poor coding habits are showing through today with people's issues. We'll get it hammered out and the app will work better than ever!

**Comment by Nexela** [comment]
1 + 3  I have been fairly busy and haven't had a chance to run the program at all until recently (even though I have been watching it!) so unfortunately the answer to this is none.  But I have tried about 4 of the previous releases all with the same results.  All fresh installs every time. Installed into my factorio install directory (e:/factorio/factorio_experimental/lunars/{version}

2. I didn't even think to look inside that folder, found a log for you!

[lmm_log.txt](https://github.com/AlyxMoon/Lunars-Factorio-Mod-Manager/files/463265/lmm_log.txt)

and my lmm_config.json

```
{
    "minWidth": 960,
    "minHeight": 840,
    "width": 960,
    "height": 1050,
    "x_loc": 0,
    "y_loc": 0,
    "mod_directory_path": "E:\\Games\\Factorio_Web\\Factorio_Experimental\\mods\\",
    "modlist_path": "E:\\Games\\Factorio_Web\\Factorio_Experimental\\mods\\mod-list.json",
    "game_path": "E:\\Games\\Factorio_Web\\Factorio_Experimental\\bin\\x64\\factorio.exe",
    "player_data_path": "E:\\Games\\Factorio_Web\\Factorio_Experimental\\player-data.json"
}
```

**Comment by AlyxMoon** [comment]
Okay excellent, I can see the problem. I made another assumption about file locations, where the base mod is located. I'm guessing that based on your setup it might be just a little bit different.

While having the base mod in the app isn't too useful at the moment, I try to find and include it in the list for thoroughness. It can be safely left out though.

If you're willing to do a workaround, open the modManagement.js file located in resources/app/inc and comment out or delete lines 95-97 (assuming you're on version 1.8.7). It'll be this bit of code:
```javascript
let gamePath = this.gamePath;
let baseInfo = `${gamePath.substr(0, gamePath.lastIndexOf('Factorio\\bin'))}Factorio/data/base/info.json`;
mods.push(JSON.parse(file.readFileSync(baseInfo, 'utf8')));
```

I'll get a fix in the app itself for the next version, but I've got to get way smarter about how I'm handling filepaths. Thanks for the patience and interest in the app though mate!

**Comment by Nexela** [comment]
Commenting out those lines lets the app run but it is just a white screen.

 Logs/settings/pics attached

[app.zip](https://github.com/AlyxMoon/Lunars-Factorio-Mod-Manager/files/463336/app.zip)

**Comment by AlyxMoon** [comment]
Do you have any mods currently in the mod directory? If not, this could be related to #63 and I'll need a few minutes to get a workaround.

**Comment by Nexela** [comment]
1 mod, I actually seen the issue so I double checked that.

**Comment by AlyxMoon** [comment]
Okay, I have a few other ideas at what could be the problem (something's causing an event not to fire that actually makes the page load).

I don't think being unable to find the base mod is the culprit here. I honestly have got no clue what to do to fix it right now, but a clear head tomorrow will help out. Sorry I can't get it useable for you at the moment, but I'll try to get a fix out tomorrow addressing this.

**Comment by Nexela** [comment]
No worries, I'll peep it out whenever you get your head wrapped around it.

**Comment by AlyxMoon** [comment]
I got a little busy this weekend so the update was delayed, my apologies.

I think v1.8.8 will actually fix things for you. I'm not sure exactly where the basemod data directory is in your environment so if you could let me know that would be appreciated. But if the app can't find the basemod it'll still work.
