### ISSUE TITLE
General Feature Request and Bug Report Thread

### ISSUE THREAD

**Issue by AlyxMoon** [AlyxMoon/Lunars-Factorio-Mod-Manager#92]
This will be for collecting any bugs noticed or features/additions so I don't forget them:

###### Features:
- [ ] Allow importing and exporting a profile

###### Improvements:
- [x] On app start, do a quick mod fetch just for installed mods so their status can be seen right away
- [x] Allow option to not fetch online mods automatically to not use uneccessary bandwidth
- [ ] Speed up app loading time
- [x] Automatic updating of installed mods
- [x] Ability to download all missing dependencies
- [ ] Improve how mods are downloaded (better control, queuing system...)

###### General Project/Code Improvements:
- [ ] Improve build scripts  
(currently the ignore flags are too broad, leaves out node modules, namely the `form-data` library used by `request` )
- [ ] Improve test coverage of already existing code
- [ ] Fully commit to using ES6 features for consistency
- [ ] Naming consistency between actions and message name between Main and Renderer Processes
- [ ] Bundle server-side code as well as the client-side code
- [ ] Extend the development environment to make better use of hot-loading
- [ ] Potentially change how logging is handled

**Comment by SeirVed** [comment]
Automatic update of installed mods

Option to auto download missing dependencies

:ok_hand:

**Comment by AlyxMoon** [comment]
Closing due to age and a planned rework
