### ISSUE TITLE
Javascript error on version 1.13

### ISSUE THREAD

**Issue by SeirVed** [AlyxMoon/Lunars-Factorio-Mod-Manager#99]
Who knows if this helps at all, but I thought you might want it.
<img width="353" alt="java error" src="https://user-images.githubusercontent.com/8616544/32300462-bfbd67f6-bfad-11e7-9102-17d28ef84393.png">

**Comment by AlyxMoon** [comment]
Hey, thanks for the bug report. I realize I had an issue with the build script, I updated the files for the 1.13 update.

**Comment by AlyxMoon** [comment]
Closing due to age and a planned rework
